site_name: documentation
site_url: https://example.com/
site_author: lots
site_description: >-
  docuementation on how to do things that I always forget how to do
repo_name: faffige/documentation
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Swtich to light mode
  font:
    text: Roboto
    code: Roboto Mono