site_name: documentation
site_url: https://example.com/
site_author: lots
site_description: >-
  docuementation on how to do things that I always forget how to do
repo_name: faffige/documentation
repo_url: https://github.com
edit_url: ""
theme:
  name: material
  favicon: assets/icon
  logo: assets/icon
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Swtich to light mode
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables